name: MinigamesParty
main: com.comze_instancelabs.minigamesparty.Main
version: 1.2.1
author: instancelabs
softdepend: [Vault]
permissions:
  mparty.sign:
    description: Gives access to create signs for joining games.
commands:
   mp:
      description: Main command
      usage: /mp [name]
   mgp:
      description: Main command
      usage: /mgp [name]
   minigamesparty:
      description: Main command
      usage: /minigamesparty [name]
